# Generated by Django 4.2.5 on 2025-05-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danhmuctailieus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiLieu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ma_tai_lieu', models.CharField(blank=True, max_length=250, null=True)),
                ('ngay_tai_lieu', models.DateField(blank=True, null=True)),
                ('ten_tai_lieu', models.CharField(max_length=250)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ngay_ky', models.DateField(blank=True, null=True)),
                ('nguoi_ky', models.CharField(blank=True, max_length=250, null=True)),
                ('file_tai_lieu', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('danh_muc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danhmuctailieus.danhmuctailieu')),
            ],
        ),
    ]
