# Generated by Django 4.2.5 on 2025-05-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phong_ban', models.CharField(max_length=255, unique=True)),
                ('thong_tin', models.TextField(blank=True, null=True)),
                ('phong_ban_cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phong_ban_con', to='phongbans.phongban')),
            ],
        ),
    ]
