# Generated by Django 4.2.5 on 2025-05-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucTaiLieu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_danh_muc', models.CharField(max_length=250)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('danh_muc_cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_muc_con', to='danhmuctailieus.danhmuctailieu')),
            ],
        ),
    ]
